[package]
name = "yaplwrs"
version = "0.1.0"
authors = ["Chloe Ross <orangesnowfox@gmail.com>"]
edition = "2018"

[lib]
name = "yaplwrs"
path = "src/lib.rs"

[dependencies]
maplit = "1.0"
proptest = "0.9"
itertools = "0.8.0"